services:
  - type: web
    name: samarkand-bot
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PIP_ONLY_BINARY
        value: :all:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_GROUP_ID
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: GOOGLE_CREDS_JSON
        sync: false
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
